# Generated by Django 4.2.3 on 2023-08-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otras_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=60)),
                ('temporadas', models.IntegerField()),
                ('pilot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='star_trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=60)),
                ('temporadas', models.IntegerField()),
                ('pilot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='star_wars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=60)),
                ('temporadas', models.IntegerField()),
                ('pilot', models.IntegerField()),
            ],
        ),
    ]
