# Generated by Django 4.2.3 on 2023-08-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otras_Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=40)),
                ('temporadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Star_Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=40)),
                ('temporadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Star_Wars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=40)),
                ('temporadas', models.IntegerField()),
            ],
        ),
    ]
