# Generated by Django 4.2.3 on 2023-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_trek',
            name='serie',
            field=models.CharField(max_length=256),
        ),
    ]
