# Generated by Django 4.2.3 on 2023-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_trek',
            name='pilot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
