# Generated by Django 4.2.3 on 2023-08-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_star_trek_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='otras_series',
            name='saga',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
